### ISSUE TITLE
Issiue with Gruvbox

### ISSUE THREAD

**Issue by Xaomin** [refact0r/monkeytype-themes#2]
When i use the gruvbox theme, it doesn't change the background, it does on botanical, but not gruv

**Comment by niposch** [comment]
Changing the url in `background-image: url("...")` to `url("https://lh3.googleusercontent.com/fife/AMPSemcMRTTVectAQJLpVkthLUMmiItOVZnjggfvoanWAe4zwaTc5ilVgyMRm-tgvt6GdgkpVj23iFW5OoC0UYnwswE_eRQN06zTWpOtdnrENp8K627WzJ28z_V4LMdqZ3owyVT6n1gW6P-rD5_Vm0pQ8K7FfVGjPqVlnf64dl46s9nES640NDvHyOBxXWgvselBuiwCN8-aNsAKr7Gl0uv51lJzS-CGnp2YejSuLs7dEEEF9IkcCS_K0C4khr8mg7nlYPoq_Kk_KQZWEoBAdGuwAxYWYTN3qjw_rZ7Z3KI4eUwDaIva_3on7GCyIFRsrrh5iAyQvmkHEH10DfO8-C2C2btfhjdHe44Eo4eiBh6EPQRhOPNKJIx7KqLUoQPEQ3U9u0rm2ZU_7rB8EzggepXSDY4ep1lzpvsYpwNDGBMUB4MwxQupw9pb3IHpZA2aEJ3AnRAXbsbo6xRd9DHlqYRveyUltGY6k7LvfSu0svoaUhtpKxYjKNIsS9Ky-s9m2kAs2W3zWQLYDO94XxyJWshTec5HMJ2I36zm7tOIOGwJpQ1EhUeDjGYF-K9Ls1Xo_lGWf3_ShiolodK9r1jlEOu2LttTGgI8sMUXl5ftKewvmx1lWsM0JW805JvkYCVVWYw0spzhT4OAaZ8nF0eIynwAhqw3ANCzjDihMu8kXi1XeXM_UjOYdWpH2vbbn9dtC0A9lWbObg9ZEOijqtAb2QmHBxycg_IQpDLgLaeH4Thk1QOJ-Vu9h506HOz98xDbFZ_XhxYVgEWTUoJUiK9zfwNrG3xgYziT4NtlQhqDdsY_SHP4ysb4ryUbb_N-vEBETLZ1AZcQqqTC8wOS4EYTQD8fEE4khmBBIUrPnEmi1uKXGpd10KiT4S-m1N2iExmJ_N2AMVQtvSBrfm8DbQ7yMiG9oxAk9a26tDGR5hEvQqQmDRtXkS4ndnA8lVgGM7Vu-C-e687aMm11fDFFfAsJAroDUlkstIBCI7WPgc0dI-B3wq6A6piQQBqGSxG10oWhvkS0KTwfFyuU-qyssVmsjgWfIidwlWUIum0s71Ytvd_KiP7MzJL6DZYojs8dlXqgnP7JDKPpv7Jyn9-6YcuW8uZwSfsUzxSFpOE98a60KqCT-ZJc_vegeBZiEk3RW8GsW1ypl5EQjAmuL9Vo4gHKNcFVeu9-xYCpEMahZ_u9gwPU9RHFzvozGYYfXbhXCbIJNN3yjnXN-KN1ul-cHSRp-XAVh93AgrKia-WgQCcW69mT_JqoOV7IFqY5ywl-J2Svtt0MF1607yB7l1rMbQnEyblRZXtlOt6Nu4HSECJZIbYGstFGZYNuBwvfqPgv1ij3OlpJNqOY6xt1Gs3KapmWU4Agkpry46cCfxohDL4Bkbt7gaxSSPLiAql4sF1fmIUK3Lx1LEdXIHJq245PIfYWrknLnkhvwzuV_o7a_JCmiBcfF0WFgn3zdl1LH0SGBIMgPzfhs0pYFlmiPu7qgPMHeq2YCViwrVqUqEYmImRQYYdLJTiXU4mreaWq6KuaYjRiKSOCgHOkkG3vw6-sfP9zEqQOwUO3d4IvqO1C=w3840-h1960?pli=1")`

Seems to fix it.
